### PR TITLE
Fix: Multiple `onFilter` call issues related to the `withAnyArgs` method

### LINKED ISSUE #258: Fix: Multiple `onFilter` + `withAnyArgs` use cases
## Bug report 

While writing some unit test cases using the `withAnyArgs` method, I came across issues for multiple `onFilter` calls introduced into the tests. At the moment, if a single `onFilter` call is used alongside `withAnyArgs`, it works correctly, but for multiple cases, it doesn't correctly pass the tests. The expected behaviour should be that this works for both single and multiple use cases using the `withAnyArgs`.

### Replication steps 

Run the following test:

```php
public function testMultipleOnFilterPassesWithAnyArgs(): void
{
    WP_Mock::bootstrap();

    /** @phpstan-ignore-next-line */
    WP_Mock::onFilter('testFilter1')
        ->withAnyArgs()
        ->reply('Filtered value 1');

    /** @phpstan-ignore-next-line */
    WP_Mock::onFilter('testFilter2')
        ->withAnyArgs()
        ->reply('Filtered value 2');

    /** @phpstan-ignore-next-line */
    WP_Mock::onFilter('testFilter3')
        ->withAnyArgs()
        ->reply('Filtered value 3');

    $filtered_value1 = apply_filters('testFilter1', 'Original value 1');
    $filtered_value2 = apply_filters('testFilter2', 'Original value 2');
    $filtered_value3 = apply_filters('testFilter3', 'Original value 3');

    $this->assertSame('Filtered value 1', $filtered_value1);
    $this->assertSame('Filtered value 2', $filtered_value2);
    $this->assertSame('Filtered value 3', $filtered_value3);

    Mockery::close();
}
```

### Expected behavior 

 The expected behaviour should be that this works correctly for both single and multiple use cases using the `withAnyArgs`.

### Screenshots 

Image

### PR DESCRIPTION
**Pull request by badasswp**
# Summary 

This PR implements a fix for an issue I discovered when using multiple `onFilter` calls with the `withAnyArgs` method.

Screenshot 2025-03-12 at 18 47 52

## Details 

While writing some unit test cases using the `withAnyArgs` method, I came across issues for multiple `onFilter` calls introduced into the tests. At the moment, if a single `onFilter` call is used alongside `withAnyArgs`, it works correctly, but for multiple cases, it doesn't correctly pass the tests. The expected behaviour should be that this works for both single and multiple use cases using the `withAnyArgs`.

This PR fixes this issue correctly.

Screenshot 2025-03-12 at 19 42 19

---

Run tests:

```php
vendor/bin/phpunit ./tests/Unit/WP_MockTest.php 
```

## Contributor checklist 

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly 
- [x] I have added tests to cover changes introduced by this pull request
- [x] All new and existing tests pass

## Testing 

```php
public function testMultipleOnFilterPassesWithAnyArgs(): void
{
    WP_Mock::bootstrap();

    /** @phpstan-ignore-next-line */
    WP_Mock::onFilter('testFilter1')
        ->withAnyArgs()
        ->reply('Filtered value 1');

    /** @phpstan-ignore-next-line */
    WP_Mock::onFilter('testFilter2')
        ->withAnyArgs()
        ->reply('Filtered value 2');

    /** @phpstan-ignore-next-line */
    WP_Mock::onFilter('testFilter3')
        ->withAnyArgs()
        ->reply('Filtered value 3');

    $filtered_value1 = apply_filters('testFilter1', 'Original value 1');
    $filtered_value2 = apply_filters('testFilter2', 'Original value 2');
    $filtered_value3 = apply_filters('testFilter3', 'Original value 3');

    $this->assertSame('Filtered value 1', $filtered_value1);
    $this->assertSame('Filtered value 2', $filtered_value2);
    $this->assertSame('Filtered value 3', $filtered_value3);

    Mockery::close();
}
```

Run test, it should pass successfully multiple times using the `withAnyArgs` method:

```bash
composer run test
```

### Reviewer checklist 

 

- [x] Code changes review
- [ ] Documentation changes review
- [x] Unit tests pass
- [x] Static analysis passes

### CODE REVIEW

**Comment by badasswp** [comment]
@agibson-godaddy Please could you help me take a look at this PR to resolve this [issue](https://github.com/10up/wp_mock/issues/258).

**Review by agibson-godaddy — COMMENTED** [review]
Thanks for putting this together! Just one suggestion.

File: php/WP_Mock/Filter.php [hunk 1]
```diff
@@ -22,7 +22,7 @@ class Filter extends Hook
     public function apply($args)
     {
         if (isset(static::$filtersWithAnyArgs[ $this->name ])) {
-            $args = array_values(static::$filtersWithAnyArgs);
+            $args = [ static::$filtersWithAnyArgs[ $this->name ] ];
```
Comment (agibson-godaddy) [inline php/WP_Mock/Filter.php]: Instead of doing this, what if we updated this line https://github.com/10up/wp_mock/blob/411d1c3cde08a995142ac735e2b83ad8fb308829/php/WP_Mock/Filter.php#L74

To be like this:

```diff
- static::$filtersWithAnyArgs[ $this->name ] = $random_value;
+ static::$filtersWithAnyArgs[ $this->name ] = [ $random_value ];
```

Then in this line we could reference it a bit more intuitively:

```suggestion
            $args = static::$filtersWithAnyArgs[ $this->name ];
```

Comment (badasswp) [reply php/WP_Mock/Filter.php]: @agibson-godaddy This makes perfect sense. I agree.

**Review by agibson-godaddy — APPROVED** [review]
Looks great, thank you!
